title = "mdp_compared config"

[NodeAddr]
NodeAddr1 = "http://192.168.20.132"
NodeAddr2 = "http://192.168.20.133"
NodeAddr3 = "http://192.168.20.135"

[Port]
Port = 8086

[Worker]
Worker = 3

[Database]
DatabaseName = "diff"
Measurement  = "diff10s"
Cqmeasurement= "diffcount10s"

#//时间间隔不能小于groupbytime的时间
[Durtime]
Starttime = "2020-01-09T00:40:16Z"
Endtime   = "2020-01-09T23:42:40Z"
#Starttime = "2019-12-24T06:15:42Z"
#Endtime   = "2019-12-24T06:30:03Z"

[GroupByTime]
ByTime = "10s"

[Mode]
CheckAndSyn = "no"